spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DBNAME}
  servlet:
    multipart:
      max-file-size: ${GROUP_FILE_MAX_FILE_SIZE:2097152}
  cloud:
    stream:
      binders:
        kafka-notification:
          type: kafka
          environment:
            spring.cloud.stream:
              kafka:
                binder:
                  brokers: ${KAFKA_NOTIFICATION_ALLOWED_CITIZEN_ENDPOINT_BROKER:${KAFKA_BROKER:}}
                  configuration:
                    sasl:
                      jaas.config: ${KAFKA_NOTIFICATION_PRODUCER_SASL_JAAS_CONFIG:}
        kafka-onboarding-notification:
          type: kafka
          environment:
            spring.cloud.stream:
              kafka:
                binder:
                  brokers: ${KAFKA_ONBOARDING_NOTIFICATION_ALLOWED_CITIZEN_ENDPOINT_BROKER:${KAFKA_BROKER:}}
                  configuration:
                    sasl:
                      jaas.config: ${KAFKA_ONBOARDING_NOTIFICATION_PRODUCER_SASL_JAAS_CONFIG:}
      bindings:
        allowedCitizen-out-0:
          binder: kafka-notification
          content-type: ${KAFKA_CONTENT_TYPE:application/json}
          destination: ${KAFKA_TOPIC_NOTIFICATION:idpay-notification-request}
        allowedCitizen-out-1:
          binder: kafka-onboarding-notification
          content-type: ${KAFKA_CONTENT_TYPE:application/json}
          destination: ${KAFKA_TOPIC_ONBOARDING_NOTIFICATION:idpay-onboarding-notification}
      kafka:
        binder:
          auto-create-topics: false
          configuration:
            heartbeat.interval.ms: ${KAFKA_CONFIG_HEARTBEAT_INTERVAL_MS:30000}
            session.timeout.ms: ${KAFKA_CONFIG_SESSION_TIMEOUT_MS:60000}
            request.timeout.ms: ${KAFKA_CONFIG_REQUEST_TIMEOUT_MS:60000}
            sasl.mechanism: ${KAFKA_CONFIG_SASL_MECHANISM:PLAIN}
            security.protocol: ${KAFKA_CONFIG_SECURITY_PROTOCOL:SASL_SSL}
        bindings:
          allowedCitizen-out-0:
            producer:
              configuration:
                client.id: allowedCitizen-producer
                connections.max.idle.ms: ${KAFKA_GROUP_PRODUCER_CONFIG_CONNECTION_MAX_IDLE_TIME:180000}
                retry.backoff.ms: ${KAFKA_GROUP_PRODUCER_CONFIG_RETRY_BO_MS:${KAFKA_RETRY_MS:10000}}
                linger.ms: ${KAFKA_GROUP_PRODUCER_CONFIG_LINGER_MS:${KAFKA_LINGER_MS:2}}
                batch.size: ${KAFKA_GROUP_PRODUCER_CONFIG_BATCH_SIZE:${KAFKA_BATCH_SIZE:16384}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

rest-client:
  initiative:
    base-url: ${INITIATIVE_MS_BASE_URL:}
  pdv-encrypt:
    http:
      retry:
        period: 100
        maxPeriod: 1
        maxAttempts: 3
    cf: ${PDV_ENCRYPT_SERVICE_CODE:pdv-ms-tokenizer}
    base-url: ${PDV_ENCRYPT_BASE_URL:}
    api.key: ${PDV_ENCRYPT_API_KEY:}
feign:
  okhttp:
    enabled: true
  client:
    config:
      pdv-ms-tokenizer:
        errorDecoder: it.gov.pagopa.group.connector.pdv.PdvClientErrorDecoder
        loggerLevel: basic
        retryer: it.gov.pagopa.group.connector.pdv.PdvClientRetryer

file:
  schedule:
    init-delay:
    fixed-rate:
    valid: #TODO not yet in use
      enabled: ${GROUP_SCHEDULE_VALIDATED_FILE_ENABLED:true}
      init-delay:
      fixed-rate:
      cron: ${GROUP_SCHEDULE_VALIDATED_FILE_CRON:5 0 0 0 * *} #Every 5 seconds
    proc-ko: #TODO not yet in use
      enabled: ${GROUP_SCHEDULE_PROC-KO_FILE_ENABLED:true}
      init-delay:
      fixed-rate:
      cron: ${GROUP_SCHEDULE_PROC-KO_FILE_CRON:10 0 0 0 * *} #Every 10 seconds
  storage:
    path: ${GROUP_FILE_ROOT_PATH:/tmp/pagopa/group}
    column_separator: ${CF_FILE_SEPARATOR_COLUMN:;}
    deletion: ${GROUP_FILE_DELETION:false}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    it.gov.pagopa: ${LOG_LEVEL_PAGOPA:INFO}
    it.gov.pagopa.group: ${LOG_LEVEL_GROUP:INFO}
    org.springframework.cloud: ${LOG_LEVEL_SPRING_CLOUD:WARN}
    org.springframework.data: ${LOG_LEVEL_SPRING_DATA:INFO}
    org.springframework.boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
    io.swagger: ${LOG_LEVEL_IO_SWAGGER:WARN}
    javax.persistence: ${LOG_LEVEL_JAVAX_PERSISTENCE:INFO}
    org.hibernate: ${LOG_LEVEL_ORG_HIBERNATE:INFO}
    org.mongodb.driver: ${LOG_LEVEL_MONGODB_DRIVER:WARN}

utils:
  task:
    execution:
      parallelPool: ${UTILS_TASK_EXECUTION_PARALLEL_POOL:8}