spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DBNAME}
  servlet:
    multipart:
      max-file-size: 2097152
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
file:
  csv:
    max-size: ${MAX_SIZE}
rest-client:
  initiative:
    base-url: ${INITIATIVE_SERVICE_BASE_URL:}

storage:
  schedule:
  file:
    path: ${CF_FILE_ROOT_PATCH:/Tmp/pagopa/cf}
    column_separator: ${CF_FILE_SEPARATOR_COLUMN:;}