spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DBNAME}
  servlet:
    multipart:
      max-file-size: 2097152
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"

rest-client:
  initiative:
    base-url: ${INITIATIVE_MS_BASE_URL:}
  pdv-encrypt:
    http:
      retry:
        period: 100
        maxPeriod: 1
        maxAttempts: 3
    cf: ${PDV_ENCRYPT_SERVICE_CODE:pdv-ms-tokenizer}
    base-url: ${PDV_ENCRYPT_BASE_URL:}
    api.key: ${PDV_ENCRYPT_API_KEY:}
feign:
  okhttp:
    enabled: true
  client:
    config:
      pdv-ms-tokenizer:
        errorDecoder: it.gov.pagopa.group.connector.pdv.PdvClientErrorDecoder
        loggerLevel: basic
        retryer: it.gov.pagopa.group.connector.pdv.PdvClientRetryer

storage:
  schedule:
  file:
    path: ${CF_FILE_ROOT_PATH:/tmp/pagopa/group}
    column_separator: ${CF_FILE_SEPARATOR_COLUMN:;}
    deletion: true

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    it.gov.pagopa: ${LOG_LEVEL_PAGOPA:INFO}
    it.gov.pagopa.group: ${LOG_LEVEL_GROUP:INFO}
    org.springframework.cloud: ${LOG_LEVEL_SPRING_CLOUD:WARN}
    org.springframework.data: ${LOG_LEVEL_SPRING_DATA:INFO}
    org.springframework.boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
    io.swagger: ${LOG_LEVEL_IO_SWAGGER:WARN}
    javax.persistence: ${LOG_LEVEL_JAVAX_PERSISTENCE:INFO}
    org.hibernate: ${LOG_LEVEL_ORG_HIBERNATE:INFO}
    org.mongodb.driver: ${LOG_LEVEL_MONGODB_DRIVER:WARN}