spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DBNAME}
management:
  endpoints:
    web:
      exposure:
        include: "*"

rest-client:
  initiative:
    base-url: ${INITIATIVE_SERVICE_BASE_URL:}

storage:
  schedule:
  file:
    path: ${CF_FILE_ROOT_PATCH:/tmp/pagopa/cf}
    column_separator: ${CF_FILE_SEPARATOR_COLUMN:;}