microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    path: /idpaygroup/(.*)
    annotations: {
      nginx.ingress.kubernetes.io/proxy-body-size=2m
    }

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

#  autoscaling:
#    enable: true
#    minReplica: 1
#    maxReplica: 2
#    pollingInterval: 30 # seconds
#    cooldownPeriod: 300 # seconds
#    triggers:
#      - type: azure-monitor
#        metadata:
#          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
#          subscriptionId: ac17914c-79bf-48fa-831e-1359ef74c1d5
#          resourceGroupName: dvopla-d-sec-rg
#          resourceURI: Microsoft.KeyVault/vaults/dvopla-d-neu-kv
#          metricName: ServiceApiHit
#          # metricNamespace: Microsoft.KeyVault/vaults
#          # metricFilter: namespace eq 'default'
#          # metricAggregationInterval: "-1:1:0"
#          metricAggregationType: Count
#          targetValue: "30"


  envConfig:
    MONGODB_DBNAME: idpay
    APPLICATIONINSIGHTS_ROLE_NAME: "idpaygroup"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    PDV_ENCRYPT_SERVICE_CODE: pdv-ms-tokenizer
    GROUP_FILE_ROOT_PATH: /tmp/group

  envConfigMapExternals:
    idpay-common:
      TZ: TZ
    rest-client:
      INITIATIVE_MS_BASE_URL: initiative_ms_base_url
      PDV_ENCRYPT_BASE_URL: pdv_decrypt_base_url
    idpay-eventhub-00:
      KAFKA_BROKER: kafka_broker
      KAFKA_CONFIG_SASL_MECHANISM: kafka_sasl_mechanism
      KAFKA_CONFIG_SECURITY_PROTOCOL: kafka_security_protocol
      KAFKA_TOPIC_NOTIFICATION: idpay_notification_request_topic
      KAFKA_TOPIC_ONBOARDING_NOTIFICATION: idpay_onboarding_notification_topic

  envSecret:
    MONGODB_URI: mongodb-connection-string
    PDV_ENCRYPT_API_KEY: pdv-api-key
    KAFKA_NOTIFICATION_PRODUCER_SASL_JAAS_CONFIG: evh-idpay-notification-request-idpay-notification-request-producer-jaas-config-idpay-00
    KAFKA_ONBOARDING_NOTIFICATION_PRODUCER_SASL_JAAS_CONFIG: evh-idpay-onboarding-notification-idpay-onboarding-notification-producer-jaas-config-idpay-00


  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
